export const Users = [
    {
      id:1,
      profilePicture: "assests/person/1.jpeg",
      username: "Aman Sharma",
    },
    {
      id:2,
      profilePicture: "assests/person/2.jpeg",
      username: "Attri Sharma",
    },
    {
      id:3,
      profilePicture: "assests/person/3.jpeg",
      username: "Harsh Yadav",
    },
    {
      id:4,
      profilePicture: "assests/person/4.jpeg",
      username: "Nitish Jha",
    },
    {
      id:5,
      profilePicture: "assests/person/5.jpeg",
      username: "Arihant Dugar",
    },
    {
      id:6,
      profilePicture: "assests/person/6.jpeg",
      username: "Piyush Bachchan",
    },
    {
      id:7,
      profilePicture: "assests/person/7.jpeg",
      username: "Shivam Chawla",
    },
    {
      id:8,
      profilePicture: "assests/person/8.jpeg",
      username: "Kunal Gupta",
    },
    {
      id:9,
      profilePicture: "assests/person/9.jpeg",
      username: "Gagan Yadav",
    },
    {
      id:10,
      profilePicture: "assests/person/10.jpeg",
      username: "Yuvraj Singh Rawat",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assests/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assests/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assests/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assests/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assests/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assests/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assests/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assests/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assests/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assests/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  